Repository cert-manager/print-your-cert, pull requests merged in 2024-03, with the labels that each got.

#13 Split up issuers
  cluster_issuer.yaml
  root_issuer_dev.yaml
  root_issuer_prod.yaml
Labels: dco-signoff: yes, lgtm, approved, size/L

#12 Add a "guestbook"
  .gitignore
  certificate.html
  cluster_issuer.yaml
  guestbook/Makefile
  guestbook/README.md
  guestbook/certificate.yaml
  guestbook/go.mod
  guestbook/go.sum
  guestbook/guestbook.service
  guestbook/index.sh
  guestbook/litestream.yml
  guestbook/main.go
  guestbook/root-ca.pem
  guestbook/write.sh
  main.go
  root-print-your-cert-ca.yaml.age
  setup_cluster.sh
Labels: size/XL, dco-signoff: yes, lgtm, approved

#16 reprint script: adapt for the new cert names and use kubectl's status patch instead of `kubectl-curl`
  reprint
Labels: dco-signoff: yes, size/M, lgtm, approved

#20 Fix Dockerfile.controller: the new `cert-card` wasn't copied into the image
  Dockerfile.controller
Labels: dco-signoff: yes, size/XS, lgtm, approved

#18 README: Move from `buildx` to `ko`
  README.md
Labels: dco-signoff: yes, lgtm, approved, size/L

#14 Readonly access for the guestbook
  guestbook/go.mod
  guestbook/go.sum
  guestbook/main.go
Labels: dco-signoff: yes, lgtm, approved, size/L

#23 improve signing errors
  after-sign.html
  certificate.html
  main.go
Labels: dco-signoff: yes

#22 Readme: update the instructions to reflect the changes made for KubeCon Paris
  README.md
Labels: dco-signoff: yes, lgtm, approved, size/L

#24 Censor emails and remove autocert
  guestbook/go.mod
  guestbook/go.sum
  guestbook/index.sh
  guestbook/main.go
Labels: dco-signoff: yes, size/M, lgtm, approved

#26 add upsert, rework db, improve local dev
  certificate.html
  guestbook/certificate.yaml
  guestbook/index-local.sh
  guestbook/index-readonly-local.sh
  guestbook/main.go
  guestbook/write-local.sh
  main.go
Labels: dco-signoff: yes

#27 Validate incoming messages
  guestbook/main.go
Labels: dco-signoff: yes, lgtm, approved

#28 Add ntfy support to guestbook
  guestbook/main.go
Labels: dco-signoff: yes, size/S

#29 Fix url
  cert-card
Labels: dco-signoff: yes, size/XS, lgtm, approved

#30 bump guestbook timeout
  main.go
Labels: dco-signoff: yes, size/XS, lgtm, approved

#31 Add user agent limits / order entries by date
  guestbook/main.go
Labels: lgtm, approved

#25 Readme updates
  README.md
Labels: dco-signoff: yes, size/M

#21 Use the built-in `kubectl patch --subresource` instead of the bespoke script `kubectl curl`
  Dockerfile.controller
  kubectl-curl
  print-your-cert-controller
Labels: dco-signoff: yes, size/L

#17 GitHub Pages: display SAN emails and add download links
  index.html
Labels: dco-signoff: yes, size/M

#33 Update dates and wording on landing page; update README
  README.md
  landing.html
Labels: dco-signoff: yes, size/S, lgtm, approved
